networks:
	agheredinet:
		name: agheredinet
		driver: bridge

services:
	nginx:
		container_name: nginx
		build: ./requirements/nginx
		imagen: nginx
		ports:
			- "443:443"
		volumes:
			- wordpress_data:/var/www/html
		networks:
			- inception_network
		restart: always
		networks: 
			-agheredinet

	mariadb:
		container_name: mariadb
		build: ./requirements/mariadb
		imagen: mariadb
		volumes:
			- mariadb_data:/var/lib/mysql
		networks:
			- agheredinet
		env_file:
 			- .env
		restart: always

	wordpress:
		container_name: wordpress
		build: ./requirements/wordpress
		imagen: wordpress
		depends_on:
			- mariadb
		volumes:
			- wordpress_data:/var/www/html
		networks:
			- agheredinet
		env_file:
			- .env
		restart: always

volumes:
	wordpress_data:
		driver: local
		driver_opts:
			device: "/home/${USER}/data/wordpress"
			o: bind
			type: none
  
	mariadb_data:
		driver: local
		driver_opts:
			device: "/home/${USER}/data/mariadb"
			o: bind
			type: none